name: Trigger auto deployment for container-app-x73d4wodrm4pw

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-x73d4wodrm4pw-AutoDeployTrigger-510f4e02-eff5-4956-857c-ac8b7123cdad.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPX73D4WODRM4PW_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPX73D4WODRM4PW_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPX73D4WODRM4PW_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPX73D4WODRM4PW_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPX73D4WODRM4PW_REGISTRY_PASSWORD }}
          containerAppName: container-app-x73d4wodrm4pw
          resourceGroup: appspacesragapp94f1943f
          imageToBuild: default/container-app-x73d4wodrm4pw:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


